{% set name = "brent_search" %}
{% set version = "2.0.1" %}
{% set sha256 = "6153e7541dc19ded662c7149fdc573d9367c41438d8c0e5dbcc751120b3ecb55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - brent_search
  commands:
    - python -c "import brent_search; brent_search.test()"

about:
  home: https://github.com/Horta/brent-search
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Brent's method for univariate function optimization.
  doc_url: https://github.com/Horta/brent-search
  dev_url: https://github.com/Horta/brent-search

extra:
  recipe-maintainers:
    - Horta
