{% set name = "brent_search" %}
{% set version = "1.0.15" %}
{% set sha256 = "07e0e7c818a698540b2cd1d5a52ed80d0b6ee9dcbf42629215598b5e7a235adb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - brent_search
  commands:
    - python -c "import brent_search; brent_search.test()"

about:
  home: https://github.com/Horta/brent-search
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Brent's method for univariate function optimization."
  doc_url: https://github.com/Horta/brent-search
  dev_url: https://github.com/Horta/brent-search

extra:
  recipe-maintainers:
    - Horta
