travis:
  secure:
    BINSTAR_TOKEN: QYEHb4f8we1ju7PIWJb+gvSgVLhCoXyhSUJLrVQZdR+rC+S6/5LpQIjMtMC3zpWOGGzv2ytSHPEcl6txPZcjqNja6sjRcGdwJhcEXrUnapAAARLxsk4YHMQ8W3W5rHLUZJsfhzgtqETut4KhNZEBsqFRDepqxBLynwV5WPiYNfZ7DOtu/HE2IBWcOhZtsH0UWy/tfW41fK+PhQkncHlXdyftTRQIhCPkSMR40Y3/pJq4Fh2iYa2amabO1uFrqCjz0CUYk946hGWeIN9LUSuHn+i9SiXoP57Qk/6o73TmB4DmdJ3beaQJm5zcDikTNaMChTQ1tiiKOe+ei1kDL3Zp71Tmb0Mt5EUWBD7FUGQzAmz/5J8GLCJc4IP2i9fJEokzJNk9Y1Ap63vGX6fqUwHpeEHW3E7t2x4zWq8JHXEcGn1kyqKMLMavkiEu3TkzdQ3n+WS7fYTb5xVjQhQe/dg+2RLhX/vI5bNZ3WWvQj8TFRJ7wywSmp9fAxRvV3XhIJFVu86HhfOZumixrgccs6EMtCgvvr/jRB3cs0+tRfScfTw3aVONRMcoOXBXyMCj0UQwtHi2pnz7g3T/9JlOnXBSS81jmA/uPvnOM8kY3uLGaDRtAtSHuqExrNGHVUjEUcQSsqEdyHLfKQb0PFhQb6zq/wYxkNqv095/eUDCOvzm8gc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
