travis:
  secure:
    BINSTAR_TOKEN: M5dI9b7DtC3GfLL9Ee31ykwtJtuTlbA4FNtf0PaT6jwsvbxptRp12WuOInPDhd51vlNhQ6uK/Zq2wC5SNENU01UwV5xEjSUlCYKvE6ka2aNXSnkIG1LVx05EF7+DY1RR96MxdrT+I8DHoMMlceFRBNPQYQUk8hDzGY7u1jf1eGOmTqzP0DbFf5Mrs1UoZRvnrB3VIjksmV+B8mhZMnTZiZz4bdLPImQhbgwQ/LuywufKcGeHuJXRF2m/sVlu+0pGDSLTbLPYMkk9CVqwLRs5W1+r834nN9PkKMrC9nOEXbn1f/XH5lkbKR8o1pMmuxSzPJFYkOYCp5lgcF5uSHHUkHZf949LNaFy34PpUDE8Q/0s4dfK+u0pQJ4Xj1pCb81yawhcm2/oDdYBGWauTaWRK3xnxpBIhURP2DR9auKoCCOeYnaQ3/6+4l8+zLUd3ZLG6mGY8qkTKvAaoVEVycGrD2NLVK8WUEVjghUsl5rhfhczXBMNPqmckfI4n3DQ6RMM6fF6/yM3QfNXgBOkyccjNVDxjwr2JY3E1kNd8oOMx9KUrh6B+X0uXeKq3mX/bf79lrygiO3H6sHWZzSvXxxotRkDFkwWOF8uQ5NXTrS9+ObmTB66L7ac4dViXWyvmbjWkLOA6hPMrjA3+7GcBcqJ2dhnt0vTBCLUh1xpAAFWGuM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
